feat(deployment): Issue 5608 basic backup restore implementation in helm hook lifecycle. (#44)
## Proposed Changes

* This pull request introduces several enhancements and updates to the
Helm chart for DotCMS. The changes focus on adding new environment
variables, improving job naming conventions, and introducing backup and
restore functionalities. The most important changes are summarized
below:

### Environment Variable Updates:
* Added multiple new environment variables related to Elasticsearch,
license management, reindexing, system status, and telemetry in the
`charts/dotcms/templates/_heplers.tpl` file.

### Job Naming and Backup/Restore Enhancements:
* Introduced new job naming helpers and backup/restore job name
definitions in the `charts/dotcms/templates/_heplers.tpl` file.
* Added a comprehensive backup and restore script in the
`charts/dotcms/templates/_heplers.tpl` file, which includes operations
for database and DotCMS data backup and restore.

### StatefulSet and InitContainers Modifications:
* Updated the `charts/dotcms/templates/statefulset.yaml` file to include
new initContainers for waiting on database readiness and handling
backup/restore operations.
* Added new containers and volume mounts for backup and restore
operations in the `charts/dotcms/templates/statefulset.yaml` file.

### Role-Based Access Control (RBAC) Updates:
* Enhanced RBAC configurations in the
`charts/dotcms/templates/rbac.yaml` file by adding new rules for
managing jobs and other resources.

### Pre-Upgrade Job Enhancements:
* Modified the pre-upgrade job script in the
`charts/dotcms/templates/job-pre-upgrade.yaml` file to handle
backup/restore operations.

These updates collectively enhance the functionality and robustness of
the DotCMS Helm chart, especially in terms of backup and restore
capabilities and environment configuration.

## Fixes
#5608

diff --git a/charts/dotcms/templates/job-pre-upgrade.yaml b/charts/dotcms/templates/job-pre-upgrade.yaml
--- a/charts/dotcms/templates/job-pre-upgrade.yaml
+++ b/charts/dotcms/templates/job-pre-upgrade.yaml
@@ -69,13 +69,12 @@ spec:
               CURR_VERSION="{{ .Values.configVersion }}"
               echo "Current Version: $CURR_VERSION, Previous Version: $PREV_VERSION"
 
-              if [ "$PREV_VERSION" != "$CURR_VERSION" ]; then
-                echo "Version changed. Upgrade required."
+              if [[ "$PREV_VERSION" != "$CURR_VERSION" || ("$BACKUP_RESTORE_ENABLED" == "true" && "$OPERATION" == "restore") ]]; then
                 UPGRADE_REQUIRED="true"
               else
-                echo "No version change detected. Upgrade not required."
                 UPGRADE_REQUIRED="false"
               fi
+              echo "Upgrade Required: $UPGRADE_REQUIRED"
               
               kubectl create configmap $CONFIGMAP_NAME \
                 --namespace {{ $namespace }} \
diff --git a/charts/dotcms/templates/statefulset.yaml b/charts/dotcms/templates/statefulset.yaml
--- a/charts/dotcms/templates/statefulset.yaml
+++ b/charts/dotcms/templates/statefulset.yaml
@@ -9,6 +9,7 @@
 {{- $licenseSecretExists := ne (lookup "v1" "Secret" $namespace $licenseSecretName) nil }}
 {{- $useLicense := default (or $licenseSecretExists .Values.license) .Values.useLicense }}
 {{- $configMapMetadata := printf "%s-%s-upgrade-metadata" .Values.customerName .Values.environment }}
+{{- $configMapMetadata := printf "%s-%s-upgrade-metadata" .Values.customerName .Values.environment }}
 ---
 apiVersion: apps/v1
 kind: StatefulSet
@@ -42,12 +43,150 @@ spec:
     spec:
       terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
       initContainers:
-        - name: wait-for-db-and-opensearch
+        - name: wait-for-job
           image: groundnuty/k8s-wait-for:no-root-v1.7
           imagePullPolicy: IfNotPresent
           args:
             - job
             - {{ include "dotcms.preUpgradeJobName" . }}-{{ .Release.Revision }}
+
+        {{- if .Values.database.local.enabled }}
+        - name: wait-for-db
+          image: bitnami/kubectl:1.32.0
+          imagePullPolicy: IfNotPresent
+          command: ["/bin/bash", "-c"]
+          args:
+            - |
+              echo "Waiting for DB to be ready..."
+              kubectl wait --for=condition=Ready pod -l app=db -n {{ $namespace }} --timeout=300s
+              echo "DB is ready."            
+        {{- end }}
+        
+        - name: check-backup-restore
+          image: bitnami/kubectl:1.32.0
+          imagePullPolicy: IfNotPresent
+          command: ["/bin/bash", "-c"]
+          args:
+            - |
+              if [ -f /tmp/backupRestore ]; then
+                rm /tmp/backupRestore
+              fi
+
+              echo "Checking backup/restore operation status from ConfigMap {{ $configMapMetadata }} in namespace {{ $namespace }}..."
+              BACKUP_RESTORE_ENABLED=$(kubectl get configmap {{ $configMapMetadata }} -n {{ $namespace }} -o=jsonpath='{.data.backupRestoreEnabled}' 2>/dev/null || echo "false")
+
+              if [ "$BACKUP_RESTORE_ENABLED" == "true" ]; then
+                echo "true" > /tmp/backupRestore
+              else
+                echo "Backup/Restore operation not detected. Skipping container"
+              fi
+          volumeMounts:
+            - name: admin-shared
+              mountPath: /tmp
+
+        - name: backup-restore
+          image: pgvector/pgvector:pg16
+          imagePullPolicy: IfNotPresent
+          command: ["/bin/bash", "-c"]
+          args:
+            - |
+              set -ex
+
+              if [ -f /tmp/backupRestore ]; then
+                echo "Backup/Restore operation detected."
+              else
+                echo "Backup/Restore operation not detected. Skipping container"
+                exit 0
+              fi
+
+              echo "Operation: ${OPERATION}"
+              BACKUP_DIR=/mnt/backup
+              DOTCMS_DATA_DIR=/data/shared
+              RESTORE_TMP_DIR=${BACKUP_DIR}/restore-temp
+
+              if [[ "$OPERATION" == "none" ]]; then
+                echo "No backup/restore required."
+                exit 0
+              fi
+
+              if [[ "${OPERATION}" == "backup" ]]; then
+                echo "Starting backup process..."
+                DB_DUMP=${BACKUP_DIR}/db-dump.sql
+                DOTCMS_DATA=${BACKUP_DIR}/dotcms-data.tar.gz
+                FINAL_BACKUP=${BACKUP_DIR}/{{ .Values.fileName | default "backup" }}-$(date +%Y%m%d%H%M%S).tar.gz
+
+                echo "Dumping database..."
+                PGPASSWORD=${DB_PASSWORD} pg_dump -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_NAME} -Fp -f ${DB_DUMP}
+
+                echo "Archiving DotCMS data..."
+                tar czf ${DOTCMS_DATA} -C ${DOTCMS_DATA_DIR} .
+
+                echo "Creating final backup..."
+                tar czf ${FINAL_BACKUP} -C ${BACKUP_DIR} db-dump.sql dotcms-data.tar.gz
+
+                echo "Backup completed successfully: ${FINAL_BACKUP}"
+
+                rm -rf ${DB_DUMP} ${DOTCMS_DATA}
+
+              elif [[ "${OPERATION}" == "restore" ]]; then
+                echo "Starting restore process..."
+                mkdir -p ${RESTORE_TMP_DIR}
+
+                echo "Extracting backup..."
+                tar xzf ${BACKUP_DIR}/{{ .Values.fileName | default "backup" }}.tar.gz -C ${RESTORE_TMP_DIR}
+
+                DB_EXISTS=$(PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME';")
+
+                if [ "$DB_EXISTS" == "1" ]; then
+                  echo "Database $DB_NAME exists. Dropping it..."
+                  PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d postgres -c "DROP DATABASE \"$DB_NAME\";"
+                else
+                  echo "Database $DB_NAME does not exist. Skipping drop."
+                fi
+
+                if ! grep -q "CREATE DATABASE" ${RESTORE_TMP_DIR}/db-dump.sql; then
+                  echo "Recreating database $DB_NAME since it's not in the backup..."
+                  PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d postgres -c "CREATE DATABASE \"$DB_NAME\" OWNER \"$DB_USERNAME\";"
+                else
+                  echo "Backup already includes CREATE DATABASE. Skipping creation."
+                fi                
+
+                echo "Restoring database..."
+                PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_NAME} -f ${RESTORE_TMP_DIR}/db-dump.sql
+
+                echo "Restoring DotCMS data..."
+                tar xzf ${RESTORE_TMP_DIR}/dotcms-data.tar.gz -C ${DOTCMS_DATA_DIR}
+
+                echo "Restore completed successfully."
+
+              else
+                echo "No valid operation specified. Exiting."
+              fi
+          env:
+            - name: OPERATION
+              value: {{ .Values.operation }}
+            - name: DB_HOST
+              value: '{{ .Values.database.host }}.{{ .Values.customerName }}.svc.cluster.local'
+            - name: DB_NAME
+              value: {{ $dbName }}
+            - name: DB_USERNAME
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "db-local-admin") }}
+                  key: username
+            - name: DB_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "db-local-admin") }}
+                  key: password
+
+          volumeMounts:
+            - name: admin-shared
+              mountPath: /tmp
+            - name: backup-volume
+              mountPath: /mnt/backup
+            - name: dotcms-shared
+              mountPath: /data/shared
 
         - name: check-upgrade
           image: bitnami/kubectl:1.32.0
@@ -66,11 +205,11 @@ spec:
                 echo "skip" > /tmp/skip                   
               fi            
           volumeMounts:
-            - name: shared-skip
+            - name: admin-shared
               mountPath: /tmp
 
         - name: dotcms-upgrade      
-          {{- include "dotcms.container.spec" (merge (dict "IsUpgradeJob" true "EnableProbes" false "ShutdownOnStartupValue" true) .) | nindent 10 }}
+          {{- include "dotcms.container.spec" (merge (dict "IsUpgradeJob" true "EnableProbes" false "ShutdownOnStartupValue" true "UseLicense" $useLicense) .) | nindent 10 }}
           command: ["/bin/bash", "-c"]
           args:
             - |
@@ -85,7 +224,7 @@ spec:
 
       containers:
         - name: dotcms
-          {{- include "dotcms.container.spec" (merge (dict "IsUpgradeJob" false "EnableProbes" true "ShutdownOnStartupValue" false) .) | nindent 10 }}
+          {{- include "dotcms.container.spec" (merge (dict "IsUpgradeJob" false "EnableProbes" true "ShutdownOnStartupValue" false "useLicense" $useLicense) .) | nindent 10 }}
       {{- if .Values.affinity.requireDifferentHosts }}
       affinity:
         podAntiAffinity:
@@ -99,11 +238,15 @@ spec:
               topologyKey: kubernetes.io/hostname
         {{- end }}
       volumes:
-      - name: shared-skip
+      - name: admin-shared
         emptyDir: {}
       - name: dotcms-shared
         persistentVolumeClaim:
           claimName: {{ include "dotcms.pvc.env.name" . }}
+      - name: backup-volume
+        hostPath:
+          path: {{ .Values.hostPath }}
+          type: DirectoryOrCreate          
       {{- if .Values.secrets.useSecretsStoreCSI }}
       - name: {{ include "dotcms.secret.provider.className"  . }}
         csi:
