#32 move upgrade logic to an initcontainer on the statefulset.

diff --git a/charts/dotcms/templates/statefulset.yaml b/charts/dotcms/templates/statefulset.yaml
--- a/charts/dotcms/templates/statefulset.yaml
+++ b/charts/dotcms/templates/statefulset.yaml
@@ -8,6 +8,7 @@
 {{- $licenseSecretName := include "dotcms.secret.shared.name" (dict "Values" .Values "secretName" "license") }}
 {{- $licenseSecretExists := ne (lookup "v1" "Secret" $namespace $licenseSecretName) nil }}
 {{- $useLicense := default (or $licenseSecretExists .Values.license) .Values.useLicense }}
+{{- $configMapMetadata := printf "%s-%s-upgrade-metadata" .Values.customerName .Values.environment }}
 ---
 apiVersion: apps/v1
 kind: StatefulSet
@@ -41,16 +42,50 @@ spec:
     spec:
       terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
       initContainers:
-        - name: init
+        - name: wait-for-db-and-opensearch
           image: bitnami/kubectl:1.32.0
           imagePullPolicy: IfNotPresent
           command: ["/bin/bash", "-c"]
           args:
             - |
-              until kubectl get pod -l app=db -n {{ $namespace }} -o jsonpath='{.items[0].status.containerStatuses[0].ready}' | grep "true"; do
-                echo "Waiting for DB..."
-                sleep 2
-              done
+              echo "Waiting for DB and OpenSearch to be ready..."
+              kubectl wait --for=condition=Ready pod -l app=db -n {{ $namespace }} --timeout=300s
+              kubectl wait --for=condition=Ready pod -l app=opensearch -n {{ $namespace }} --timeout=300s
+              echo "DB and OpenSearch are ready."
+
+        - name: check-upgrade
+          image: bitnami/kubectl:1.32.0
+          imagePullPolicy: IfNotPresent
+          command: ["/bin/bash", "-c"]
+          args:
+            - |
+              if [ -f /tmp/skip ]; then
+                rm /tmp/skip
+              fi
+              echo "Checking upgrade status from ConfigMap {{ $configMapMetadata }} in namespace {{ $namespace }}..."
+              UPGRADE_REQUIRED=$(kubectl get configmap {{ $configMapMetadata }} -n {{ $namespace }} -o=jsonpath='{.data.upgradeRequired}' 2>/dev/null || echo "false")
+              echo "Upgrade required value: $UPGRADE_REQUIRED"
+              if [ "$UPGRADE_REQUIRED" != "true" ]; then
+                echo "Upgrade not required. Marking skip..."
+                echo "skip" > /tmp/skip                   
+              fi            
+          volumeMounts:
+            - name: shared-skip
+              mountPath: /tmp
+
+        - name: dotcms-upgrade      
+          {{- include "dotcms.container.spec" (merge (dict "IsUpgradeJob" true "EnableProbes" false "ShutdownOnStartupValue" true) .) | nindent 10 }}
+          command: ["/bin/bash", "-c"]
+          args:
+            - |
+              if [ -f /tmp/skip ]; then
+                echo "Upgrade not required. Skipping container execution."
+              else
+                echo "Upgrade required. Launching original entrypoint..."
+                echo "env DOT_SHUTDOWN_ON_STARTUP=$DOT_SHUTDOWN_ON_STARTUP"
+                exec /srv/entrypoint.sh dotcms
+              fi
+              exit 0
 
       containers:
         - name: dotcms
@@ -68,6 +103,8 @@ spec:
               topologyKey: kubernetes.io/hostname
         {{- end }}
       volumes:
+      - name: shared-skip
+        emptyDir: {}
       - name: dotcms-shared
         persistentVolumeClaim:
           claimName: {{ include "dotcms.pvc.env.name" . }}
